### PR TITLE
update geodetic function and derived calculations

### PR DESCRIPTION
**Pull request by stronnag**
Continue / refine  the work in #23:

* New bearing / distance function more suited to desktop CPUs with FPUs and efficient native FP / transcendental functions.
* Provide more accurate distances for more aerobatic flights
* Provide more obvious (from a navigation point of view) column names
* Provide more correct bearings / relative bearings
* Avoid -ve mAh / Km values

### CODE REVIEW

**Comment by danarrib** [comment]
Super nice @stronnag . 
I could not test it this weekend, but I'll do it this week.

**Comment by stronnag** [comment]
Any test? Comments ?

**Comment by danarrib** [comment]
I am sorry Jonathan, I could not test... That week was super busy and now I'm recovering from a surgery so I'm avoiding the computer this days... I guess I'll be able to test it next week.

**Comment by stronnag** [comment]
No hurry, I'll probably push out an RC2 next week anyway.

**Comment by danarrib** [comment]
Hey @stronnag, I had a chance to test it tonight. 
It works fine for almost everything, it fixes that distance calculations on your logs and on my logs it still get correct distances, which is super nice.

It only gets strange results on the last 3 lines:
image

It's probably something related to the home point changing on this lines. On my previous code I had a workaround to skip setting the home point if it changes by several kilometers:

image

I guess it was dropped on your version.

Also, you removed the "azimuth" column, and added on it's place the "homeDirection" column. 
The home direction is correct, but it's exactly the opposite of the azimuth. It is not correct to replace one by the other, they are different data.

Azimuth is the direction where an antenna on the home point should point to aim directly to the aircraft.

Home direction is the direction where the aircraft should fly to aim directly to the home point.

So the home direction is 180º of azimuth, and vice versa. (If home direction is 30, azimuth is 210, if home direction is 300, azimuth is 120).

I guess we can keep the home direction, it's a nice addition... But It would be nice to keep the azimuth too, so Dashware can overlay it.

**Comment by stronnag** [comment]
> It only gets strange results on the last 3 lines:
> image
> 
Seems like the log is totally corrupt here (the locations are bizarre, outside +/- 90, +/- 180, the number of satellites is impossible etc.) Can I see this log file.

> It's probably something related to the home point changing on this lines. On my previous code I had a workaround to skip setting the home point if it changes by several kilometers:
> 
> image

We can probably detect detect such corruption in other ways (i.e. the number of sats is impossible, the locations are impossible), I'd be grateful to see one or more example logs. Not just at the end.

> I guess it was dropped on your version.

I've never seen such corrupted logs (I have a large donated collection).  

> Also, you removed the "azimuth" column, and added on it's place the "homeDirection" column.
> The home direction is correct, but it's exactly the opposite of the azimuth. It is not correct to replace one by the other, they are different data.

I'll add azimuth back.

btw. Work in progress Google Earth viewer (or rather smart KML/Z generator). Context coded flight points based on mode). Pop-up info at any point. Animation.

Screenshot-20201227203722-1157x627

**Comment by danarrib** [comment]
> Can I see this log file.

Here it is: [LOG00022.zip](https://github.com/iNavFlight/blackbox-tools/files/5747245/LOG00022.zip)

> I'll add azimuth back.

Thanks! :-)

> Google Earth viewer

Looking good! Can't wait to see!

**Comment by stronnag** [comment]
Thanks for the log. In my logs, the home gets set once and we're done. In LOG00022, it gets get numerous times. I think I'll address this in `parser.c` (where it's set from the history).

* My log : no changes
* LOG00022 --- wow, so change big changes. 

```
Numbers are previous integer lat,lon, new int lat, lon, latdiff, londiff                     
GPS HOME JUMP 382256 1772900646 -234576531 -468210553 234958787 2241111199
GPS HOME JUMP -33 7502 -234576531 -468210553 234576498 468218055
GPS HOME JUMP 21623396 -18955155 -234576531 -468210553 256199927 449255398
GPS HOME JUMP -6 6671 -234576531 -468210553 234576525 468217224
GPS HOME JUMP 31 -4811 -234576531 -468210553 234576562 468205742
GPS HOME JUMP 180979 -6596 -234576531 -468210553 234757510 468203957
GPS HOME JUMP 32 -17 -234576531 -468210553 234576563 468210536
GPS HOME JUMP -40 106766127 -234576531 -468210553 234576491 574976680
GPS HOME JUMP 0 0 -234576531 -468210553 234576531 468210553
GPS HOME JUMP 33 -67139258 -234576531 -468210553 234576564 401071295
GPS HOME JUMP -2 56 -234576531 -468210553 234576529 468210609
GPS HOME JUMP 1626 -46 -234576531 -468210553 234578157 468210507
GPS HOME JUMP 2663 1082 -234576531 -468210553 234579194 468211635
GPS HOME JUMP -2 26 -234576531 -468210553 234576529 468210579
GPS HOME JUMP 0 7880 -234576531 -468210553 234576531 468218433
GPS HOME JUMP -4982 7538 -234576531 -468210553 234571549 468218091
GPS HOME JUMP 1107974756 -130 -234576531 -468210553 1342551287 468210423
GPS HOME JUMP -25 -86447285 -234576531 -468210553 234576506 381763268
GPS HOME JUMP -42 5253 -234576531 -468210553 234576489 468215806
GPS HOME JUMP 8 6594 -234576531 -468210553 234576539 468217147
GPS HOME JUMP 18 -2 -234576531 -468210553 234576549 468210551
GPS HOME JUMP -11 450327385 -234576531 -468210553 234576520 918537938
GPS HOME JUMP 39 239834 -234576531 -468210553 234576570 468450387
GPS HOME JUMP -52 -31 -234576531 -468210553 234576479 468210522
GPS HOME JUMP -169154 -50 -234576531 -468210553 234407377 468210503
GPS HOME JUMP 4 -289 -234576531 -468210553 234576535 468210264
GPS HOME JUMP 49 2625 -234576531 -468210553 234576580 468213178
GPS HOME JUMP -40 -2 -234576531 -468210553 234576491 468210551
GPS HOME JUMP 56 -53 -234576531 -468210553 234576587 468210500
GPS HOME JUMP -694999 -90300495 -234576531 -468210553 233881532 377910058
GPS HOME JUMP 2379 -11 -234576531 -468210553 234578910 468210542
GPS HOME JUMP 39 -40 -234576531 -468210553 234576570 468210513
GPS HOME JUMP 1 7430 -234576531 -468210553 234576532 468217983
GPS HOME JUMP 7582 -8019 -234576531 -468210553 234584113 468202534
GPS HOME JUMP -403 -1038 -234576531 -468210553 234576128 468209515
GPS HOME JUMP 4 464 -234576531 -468210553 234576535 468211017
GPS HOME JUMP 48 -33 -234576531 -468210553 234576579 468210520
GPS HOME JUMP -1345177851 476083 -234576531 -468210553 1110601320 468686636
GPS HOME JUMP -1316 -51692178 -234576531 -468210553 234575215 416518375
GPS HOME JUMP 10 -134346 -234576531 -468210553 234576541 468076207
GPS HOME JUMP 34 6 -234576531 -468210553 234576565 468210559
GPS HOME JUMP -1455122811 6331 -234576531 -468210553 1220546280 468216884
GPS HOME JUMP -4847 57 -234576531 -468210553 234571684 468210610
GPS HOME JUMP 1836 15 -234576531 -468210553 234578367 468210568
GPS HOME JUMP -291 -42 -234576531 -468210553 234576240 468210511
GPS HOME JUMP -18 3277 -234576531 -468210553 234576513 468213830
GPS HOME JUMP 48 -1102239106 -234576531 -468210553 234576579 634028553
GPS HOME JUMP -29 5168 -234576531 -468210553 234576502 468215721
GPS HOME JUMP -61 -1443 -234576531 -468210553 234576470 468209110
GPS HOME JUMP -2 -4489 -234576531 -468210553 234576529 468206064
GPS HOME JUMP 321915 624656 -234576531 -468210553 234898446 468835209
GPS HOME JUMP 144 -6751 -234576531 -468210553 234576675 468203802
GPS HOME JUMP 16865774 1920 -234576531 -468210553 251442305 468212473
GPS HOME JUMP -4 10 -234576531 -468210553 234576527 468210563
GPS HOME JUMP -3842 -4858 -234576531 -468210553 234572689 468205695
GPS HOME JUMP 19 4161 -234576531 -468210553 234576550 468214714
GPS HOME JUMP -33 486753451 -234576531 -468210553 234576498 954964004
GPS HOME JUMP 476 1221 -234576531 -468210553 234577007 468211774
GPS HOME JUMP 57 -62 -234576531 -468210553 234576588 468210491
GPS HOME JUMP 48 29 -234576531 -468210553 234576579 468210582
GPS HOME JUMP 2433 -1868 -234576531 -468210553 234578964 468208685
GPS HOME JUMP 90642264 578695 -234576531 -468210553 325218795 468789248
GPS HOME JUMP -2322 696573 90642264 578695 90644586 117878
GPS HOME JUMP -43 31 -2322 696573 2279 696542
GPS HOME JUMP -1800 41 -2322 696573 522 696532
GPS HOME JUMP -5961 1833360544 -2322 696573 3639 1832663971
GPS HOME JUMP 564617 63011712 -2322 696573 566939 62315139
GPS HOME JUMP 0 -28 -2322 696573 2322 696601
GPS HOME JUMP -6756 1238 -2322 696573 4434 695335
GPS HOME JUMP 42 -55 -2322 696573 2364 696628
GPS HOME JUMP 228923 477061 -2322 696573 231245 219512
GPS HOME JUMP -6809 56 -2322 696573 4487 696517
GPS HOME JUMP -34 0 -2322 696573 2288 696573
GPS HOME JUMP 2 -888313 -2322 696573 2324 1584886
GPS HOME JUMP -387268 37 -2322 696573 384946 696536
GPS HOME JUMP 59 -591979 -2322 696573 2381 1288552
GPS HOME JUMP 2686 -36 -2322 696573 5008 696609
GPS HOME JUMP -8046 52 -2322 696573 5724 696521
GPS HOME JUMP 53 41 -2322 696573 2375 696532
GPS HOME JUMP -1 -55 -2322 696573 2321 696628
GPS HOME JUMP -11 40 -2322 696573 2311 696533
GPS HOME JUMP -787721 -1 -2322 696573 785399 696574
GPS HOME JUMP -3559 -1807526821 -2322 696573 1237 1808223394
GPS HOME JUMP 61 869227 -2322 696573 2383 172654
GPS HOME JUMP 18 181260919 -2322 696573 2340 180564346
GPS HOME JUMP 54 2899 -2322 696573 2376 693674
GPS HOME JUMP 47 -48 -2322 696573 2369 696621
GPS HOME JUMP 39 63 -2322 696573 2361 696510
GPS HOME JUMP 14 4066 -2322 696573 2336 692507
GPS HOME JUMP 57 0 -2322 696573 2379 696573
GPS HOME JUMP 4307 -50 -2322 696573 6629 696623
GPS HOME JUMP -32 -1002177 -2322 696573 2290 1698750
GPS HOME JUMP 5036 -21 -2322 696573 7358 696594
GPS HOME JUMP 6306 343511 -2322 696573 8628 353062
GPS HOME JUMP -18 2 -2322 696573 2304 696571
GPS HOME JUMP 36 -42 -2322 696573 2358 696615
GPS HOME JUMP -42 7174 -2322 696573 2280 689399
GPS HOME JUMP 531154 61449283 -2322 696573 533476 60752710
GPS HOME JUMP 63 3098 -2322 696573 2385 693475
GPS HOME JUMP 47 465362 -2322 696573 2369 231211
GPS HOME JUMP -8020 35 -2322 696573 5698 696538
GPS HOME JUMP 21 5120 -2322 696573 2343 691453
GPS HOME JUMP -37 37 -2322 696573 2285 696536
GPS HOME JUMP -32 -131744948 -37 37 5 131744985
GPS HOME JUMP 33 631731 -37 37 70 631694
GPS HOME JUMP -81443976 -47 -37 37 81443939 84
GPS HOME JUMP 72126 31 -37 37 72163 6
GPS HOME JUMP 1 6663 72126 31 72125 6632
GPS HOME JUMP 0 930958 72126 31 72126 930927
GPS HOME JUMP 1 -1802 72126 31 72125 1833
GPS HOME JUMP -1827 -849003586 -8 37 1819 849003623
GPS HOME JUMP 26 -309469 -8 37 34 309506
GPS HOME JUMP -60 550157211 -8 37 52 550157174
GPS HOME JUMP 976562 -15 -8 37 976570 52
GPS HOME JUMP 48761521 -7 12 -10 48761509 3
GPS HOME JUMP 44009787 4 12 -10 44009775 14
GPS HOME JUMP -290421 1746204346 12 -10 290433 1746204356
GPS HOME JUMP 172947475 42 12 -10 172947463 52
GPS HOME JUMP 29 5969230 12 -10 17 5969240
GPS HOME JUMP 108644 -5 12 -10 108632 5
GPS HOME JUMP 995518 318934 12 -10 995506 318944
GPS HOME JUMP 22 -4 995518 318934 995496 318938
GPS HOME JUMP -3 -4 995518 318934 995521 318938
GPS HOME JUMP 31 613034 995518 318934 995487 294100
GPS HOME JUMP 33 1107764081 995518 318934 995485 1107445147
GPS HOME JUMP -60 1618 995518 318934 995578 317316
GPS HOME JUMP 1769758368 -53 995518 318934 1768762850 318987
GPS HOME JUMP 29 6 995518 318934 995489 318928
GPS HOME JUMP -4 -15 995518 318934 995522 318949
GPS HOME JUMP 52 41 995518 318934 995466 318893
GPS HOME JUMP 40 -151543506 995518 318934 995478 151862440
GPS HOME JUMP 26 23 995518 318934 995492 318911
GPS HOME JUMP -231 8 995518 318934 995749 318926
GPS HOME JUMP -4 -2 995518 318934 995522 318936
GPS HOME JUMP 32 14 995518 318934 995486 318920
GPS HOME JUMP -40 28 995518 318934 995558 318906
GPS HOME JUMP -4280 0 995518 318934 999798 318934
GPS HOME JUMP 46 40 995518 318934 995472 318894
GPS HOME JUMP -976371 -866477 995518 318934 1971889 1185411
GPS HOME JUMP 48 -4894 995518 318934 995470 323828
GPS HOME JUMP 61 40 995518 318934 995457 318894
GPS HOME JUMP 729184 -749110 995518 318934 266334 1068044
GPS HOME JUMP 1123 59744 995518 318934 994395 259190
GPS HOME JUMP -46 646 995518 318934 995564 318288
GPS HOME JUMP 7 4 995518 318934 995511 318930
GPS HOME JUMP 38 -121365 995518 318934 995480 440299
GPS HOME JUMP 59 375145 38 -121365 21 496510
GPS HOME JUMP 12 55 38 -121365 26 121420
GPS HOME JUMP -14 -6792 38 -121365 52 114573
GPS HOME JUMP -31 -3431 38 -121365 69 117934
GPS HOME JUMP 61 0 38 -121365 23 121365
GPS HOME JUMP -58 6721 38 -121365 96 128086
GPS HOME JUMP 122438493 22 38 -121365 122438455 121387
GPS HOME JUMP -19 -464680 38 -121365 57 343315
GPS HOME JUMP -2 -6563 38 -121365 40 114802
GPS HOME JUMP 5525 -59 38 -121365 5487 121306
GPS HOME JUMP 1030401 -235 38 -121365 1030363 121130
GPS HOME JUMP -29 22 38 -121365 67 121387
GPS HOME JUMP 45 -25 38 -121365 7 121340
GPS HOME JUMP -41 370253 38 -121365 79 491618
GPS HOME JUMP 28 2647 38 -121365 10 124012
GPS HOME JUMP -5587 2 38 -121365 5625 121367
GPS HOME JUMP 42 -24 38 -121365 4 121341
GPS HOME JUMP -47 22338896 38 -121365 85 22460261
GPS HOME JUMP -2021 -271 -47 22338896 1974 22339167
GPS HOME JUMP 29 -2 -47 22338896 76 22338898
GPS HOME JUMP 38 39 -47 22338896 85 22338857
GPS HOME JUMP 28 -424 -47 22338896 75 22339320
GPS HOME JUMP -37 37 -47 22338896 10 22338859
GPS HOME JUMP -32 -1198138548 -37 37 5 1198138585
GPS HOME JUMP -32 -240796852 -37 37 5 240796889
GPS HOME JUMP -53513 4725 -37 37 53476 4688
GPS HOME JUMP 18 51395479 -37 37 55 51395442
GPS HOME JUMP -559973 41 -37 37 559936 4
GPS HOME JUMP -1740 -40565834 -37 37 1703 40565871
GPS HOME JUMP 3316 -928612 -37 37 3353 928649
GPS HOME JUMP -1315 21324 -37 37 1278 21287
GPS HOME JUMP -49 -306024 -37 37 12 306061
GPS HOME JUMP 509169 58 -47 -531 509216 589
GPS HOME JUMP -34 -866827 -47 -531 13 866296
GPS HOME JUMP 52 1727299928 -47 -531 99 1727300459
GPS HOME JUMP -54963959 -23 57 21 54964016 44
GPS HOME JUMP -596691 2 57 21 596748 19
GPS HOME JUMP -3615 7996117 57 21 3672 7996096
```

**Comment by danarrib** [comment]
>  wow, so change big changes.

Yeah... Funny thing is: I didn't changed the home point during this flight. 
I don't even have the HOME RESET mode available on my aircrafts.

INAV 2.3 somehow logged this records... But I don't know why. It's probably not a bug on INAV, but some feature we are not understanding.

**Comment by stronnag** [comment]
It's a bug somewhere, these are huge differences, I have 100s of logs, never seen this IIRC (I'll analyse them all). Anyway, once it's  resolved you may recognise this:
Screenshot-20201228133502-1157x662

mwp's replay colour scheme (cyan: piloted, yellow: RTH, purple: Cruise, green PH/AH, light blue launch).

**Comment by stronnag** [comment]
Daniel, what do you think is a reasonable home change ? 500m, 1km ? 
I'll go for 500m unless you have a strong view otherwise.

**Comment by danarrib** [comment]
I guess it's ok to allow "a few kilometers" of home change. I'm thinking on a scenario where someone is flying following a highway, and the pilot is inside a car following the aircraft. Then pilot can reset home from time to time to allow the aircraft to return to a safe place during this trip (using the HOME RESET flight mode).

I noticed that every Home point jump has big distances from each other (a lot more than 100 km). So it's safe to allow something between 10 and 50 km distance.

**Comment by stronnag** [comment]
I think I'll leave it in the land of the sane for the next RC.
Can you see of #27 breaks anything.

**Comment by danarrib** [comment]
Ok, looks like nothing broke. Everything works fine on master.

**Pull request merged**
